bridge:
  name: "HKP"
  pincode: "00000000"

accessories:
  - id: 100001
    name: "Some Light"
    typebyte: 5
    services:
      - typestring: "43"
        characteristics:
          - type: "On"
            poll: 60
            set: "./scripts/turn_light.sh"
            get: "./scripts/get_light.sh"
